### ISSUE TITLE
如果是带链接的轮播图，点击到另一个页面，然后返回，发现轮播图轮播错误。

### ISSUE THREAD

**Issue by duanxb** [pspgbhu/Vue2-C-Swipe-Mobile#5]
如果是带链接的轮播图，点击到另一个页面，然后返回，发现轮播图轮播错误，速度也变快了。希望能解决这个bug

**Comment by pspgbhu** [comment]
我最近正准备全面的改写一下这个组件，到时候完工了这些问题应该就不存在了

**Comment by duanxb** [comment]
你能大约知道是哪里出了问题吗？我想暂时改一下，先用着。
我发现的问题是：当按长时间按住图片或者是图片加链接 点击链接跳转的时候都会出现问题。

**Comment by pspgbhu** [comment]
如果你要急着用的话，可以改一下。如果不着急我建议先不要改，因为我正在重写全部的逻辑，准备发布 2.0 了，如果你感兴趣，到时候可以帮忙维护 2.0 版本的代码。

**Comment by lzd358194530** [comment]
我修改了你的轮播图  改了几个bug github 使用不熟悉 不会贡献代码·····

**Comment by pspgbhu** [comment]
2.0 发布了，重写了逻辑，同时也解决了已知的 bug
